
sensor:
#ADC2 pins cannot be used when Wi-Fi is used
### in use the motor use 15-20 mV. At endstop, it raise to 50 mV
  - platform: adc
    pin: GPIO36
    name: "BEMF 1" #CH1 + CH2
    update_interval: 4ms
    attenuation : 0db
    id : BEMF_1_2_sensor_ADC
    accuracy_decimals: 3
    filters:
      -  sliding_window_moving_average:
          window_size: 50
          send_every: 25
          send_first_at: 1
      -  skip_initial: 2

  - platform: adc
    pin: GPIO39
    name: "BEMF 2" #CH3 + CH4
    update_interval: 4ms
    attenuation : 0db
    id : BEMF_3_4_sensor_ADC
    accuracy_decimals: 3
    filters:
      -  sliding_window_moving_average:
          window_size: 50
          send_every: 25
          send_first_at: 1
      -  skip_initial: 2

  - platform: adc
    pin: GPIO34
    name: "BEMF 3" #CH5 + CH6
    update_interval: 4ms
    attenuation : 0db
    id : BEMF_5_6_sensor_ADC
    accuracy_decimals: 3
    filters:
      - sliding_window_moving_average:
          window_size: 50  
          send_every: 25
          send_first_at: 1
      - skip_initial: 2

  - platform: adc
    pin: GPIO35
    name: "BEMF 4" #CH7 + CH8
    update_interval: 4ms
    attenuation : 0db
    id : BEMF_7_8_sensor_ADC
    accuracy_decimals: 3
    filters:
      - sliding_window_moving_average:
          window_size: 50  
          send_every: 25
          send_first_at: 1
      - skip_initial: 2

