mqtt:
 broker: 192.168.20.251

sensor:
  - platform: mqtt_subscribe
    name: "Ot.Bl.Th1 Temperature"
    id: ATC_8DC797_Temperature
    topic: Hz/Hz.Wz.Th_Climate/mT_out
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Bd.Bl.Th1 Temperature"
    id: ATC_51C199_Temperature
    topic: Hz/Hz.Bd.Th_Climate/mT_ble
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C13851C199/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Me.Bl.Th1 Temperature"
    id: ATC_999EC2_Temperature
    topic: Hz/Hz.Me.Th_Climate/mT_blw
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C138999EC2/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Me.Bl.Th2 Temperature"
    id: ATC_BE2C2D_Temperature
    topic: Hz/Hz.Me.Th_Climate/mT_blt
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C138BE2C2D/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"


  - platform: mqtt_subscribe
    name: "Ku.Bl.Th1 Temperature"
    id: ATC_254DD2_Temperature
    topic: Hz/Hz.Ku.Th_Climate/mT_bl1
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C138254DD2/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Wz.Bl.Th1 Temperature"
    id: ATC_7E0406_Temperature
    topic: Hz/Hz.Wz.Th_Climate/mT_blt
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C1387E0406/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Wz.Bl.Th2 Temperature"
    id: ATC_C9FA01_Temperature
    topic: Hz/Hz.Wz.Th_Climate/mT_blo
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C138C9FA01/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Wz.Bl.Th3 Temperature"
    id: ATC_06F092_Temperature
    topic: Hz/Hz.Wz.Th_Climate/mT_blw
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C13806F092/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

  - platform: mqtt_subscribe
    name: "Sz.Bl.Th1 Temperature"
    id: ATC_E30A6D_Temperature
    topic: Hz/Hz.Gz.Th_Climate/mT_bl1
#    topic: home/opmqgw_BLE/BTtoMQTT/A4C138E30A6D/tempc
    accuracy_decimals: 3
    device_class: "temperature"
    unit_of_measurement: "°C"
    filters:
      - heartbeat: "60s"

