
time:
- platform: sntp
  timezone : ${TZ}
  servers:  [owrt.home.arpa, 1.pool.ntp.org , 2.pool.ntp.org]
  on_time:
  - seconds: 0
    minutes: 0
    hours: 5
    days_of_week: MON #monday at 5
    then:
      - switch.toggle: floor_heating_ctrl_reboot


